// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gdmyulkiljgozjpeqyjj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdkbXl1bGtpbGpnb3pqcGVxeWpqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5NTMyMTAsImV4cCI6MjA2NDUyOTIxMH0.YeFk6coenHXsWCSnDzKNZ9LS3w1uCqcLThVPk0RssaM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);